name: ci
on:
	push:
    branches: 
    	- master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
			- name: setup nodejs
			  uses: actions/setup-node@v1.4.2
			  with:
			  	node-version: 12

      - uses: actions/checkout@v2

      - name: yarn install
        run: yarn install        

      - name: build
        run: node do build

      - name: test
        run: node do test
